### ISSUE TITLE
Memory consumption is high while syncing

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#1016]
@pacu [discovered this](https://github.com/zcash/ZcashLightClientKit/pull/1009#discussion_r1181897594) while reviewing #1009. After some debugging I found out that same happens in the main branch. So it's not related to the parallel downloading.

**Comment by Chlup** [comment]
This is the stack trace that allocates most of the memory:
<img width="343" alt="Screenshot 2023-05-02 at 12 07 05" src="https://user-images.githubusercontent.com/506376/236402713-ce740466-213e-4f3c-9ec2-ab790f2a26cc.png">

**Comment by Chlup** [comment]
It looks like that this is problem only when running the SDK in the iOS simulator. On real device (when I run sync in the Sample app) memory consumption stops at ~148MB and then it is slowly decreasing and stops around 60MB. It is super strange. But it also means that it doesn't affect any real user.
<img width="852" alt="Screenshot 2023-05-03 at 12 37 34" src="https://user-images.githubusercontent.com/506376/236402994-031e8afe-f817-4b54-9918-1a6d32f5ab40.png">

**Comment by pacu** [comment]
shall we open a ticket in Swift-GRPC itself?

**Comment by tw0po1nt** [comment]
@pacu I'm at the point with the secant version of nighthawk that I am actually successfully creating and importing wallets. However, whenever I try to import an wallet from a bit ago (around 270,000 blocks ago) and run it on device (iPhone SE 3rd generation, iOS 16.3.1), my memory is ballooning to the point where the system kills it. So I do think this may be an issue beyond the simulator.

**Comment by pacu** [comment]
> @pacu I'm at the point with the secant version of nighthawk that I am actually successfully creating and importing wallets. However, whenever I try to import an wallet from a bit ago (around 270,000 blocks ago) and run it on device (iPhone SE 3rd generation, iOS 16.3.1), my memory is ballooning to the point where the system kills it. So I do think this may be an issue beyond the simulator.

thanks for reporting this. We are still chasing this down, any additional context or hints are welcome!

**Comment by Chlup** [comment]
@tw0po1nt Can you please run your app from the Xcode and then make screenshot of memory consumption graph? So we know what is exactly happening on your device?

**Comment by pacu** [comment]
Tested on iPhone 7 that workaround on 0.22.0-beta works properly
