### ISSUE TITLE
Logic error in `SyncStatus` enum

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1154]
### Describe the issue
In `Synchronizer.swift`, there is an enum `SyncStatus` that provides the following 3 convenience properties:

```
public var isSyncing: Bool {
        guard case .syncing = self else { return true }
        return false
}
    
public var isSynced: Bool {
       guard case .upToDate = self else { return true }
       return false
}

public var isPrepared: Bool {
       guard case .unprepared = self else { return false }
       return true
}
```

There are a couple issues with this:
1. The logic is simply wrong. Each of these is inverted.
2. Using guard here is confusing (and probably what led to this logic error). Generally, guard is used to bail early if a precondition is unmet. In this case, we're mapping a case value to a Bool flag. Better to use a simple if check, which is in fact what the analogous `InternalSyncStatus` does. In fact, one could argue the implementation for both should be the same for consistency.

#### If so, please list the steps to reproduce below:
1. Try to check on the sync status by using one of these utility properties.

### Expected behaviour
Tell us what should happen
In my use case, if the SDK is syncing (thus isSyncing should return true), I want to show an indeterminate progress bar. 

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

The app syncs with no loading indicator, and when the sync finished, the loading indicator shows (because the logic is reversed)

- App Version: 
- iOS Version:
- Device: (if applies)

**Comment by LukasKorba** [comment]
You are right, the logic is inverted, at the same time, the computed variables are not used anywhere in the SDK as well as Sample and secant apps or tests. From this point of view, we could remove it completely but since it's a public API, the fix is a good solution.
