### ISSUE TITLE
Reorg Test Case: Outbound Block Height Difference

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#118]
**Case is:** The wallet sends a transaction which will contain change, the transaction is mined, a reorg occurs, making the pending transaction "unmined", and then is picked up in a different block post-reorg.

**Outcome:** after the reorg, the transaction shows as pending, the tx is picked up in the next block, and stored locally with correct block information.

**Comment by pacu** [comment]
it's finished but we need a dataset with funds at a given height
