### ISSUE TITLE
Extend the overall range after chain tip update

### ISSUE THREAD

**Issue by LukasKorba** [zcash/ZcashLightClientKit#1211]
Follow up ticket for #1207.

The logic works but whenever a few new blocks have been minted it should be reflected in total progress range. When the range extends a bit, it's questionable what happens to the %, the bad UX would be to lower it so try to figure out the solution.

**Comment by nuttycom** [comment]
This will be more easily solved after librustzcash/#900 is complete.

**Comment by nuttycom** [comment]
#434 is an earlier statement of this problem and zcash/librustzcash#865 is the ticket tracking the solution in zcash-client-backend, so I think that this can now be closed in favor of #434
