### ISSUE TITLE
Re Org Tests: inbound tx, last transaction disappears and is never mined

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#124]
Transaction was included in a block, and then is not included in a block after a reorg, and expires.

**Comment by pacu** [comment]
this means:
- wallet receives tx at height X, 
- a reorg happens at height X + Z,   0 <= Z < 10
- wallet syncs up to X + 10
- tx is never mined.

conditions: no other txs are receivec between X and X + 10
success: balance at X + 10 equals balance pre Tx , Tx does not show up in  received transactions list.

**Comment by pacu** [comment]
@gmale @braddmiller could you double check test steps above?

**Comment by braddmiller** [comment]
Those steps look right to me, though I think we need to have a UX discussion around what to do with the transaction that disappeared, but that's well outside the realm of this test

**Comment by gmale** [comment]
I think the gist is correct but the variables seem off (and I think maybe some of the pluses should be minuses) so I'll restate it using hypothetical heights:

- wallet receives tx at height 663160 (X),
- a reorg happens at height 663158 (X - 2) but we don't notice until we receive block 663161 (X + 1)
- wallet rewinds to 663151 ((X + 1) - 10)
- wallet then begins syncing back to 663160 (X), when it reaches that block the transaction that was there, is gone
- wallet continues syncing to 663170 (X + 10), at which point the wallet changes the status of the original tx from "pending" to "expired"

**Comment by pacu** [comment]
I think that librustzcash works in a way that the reorged transaction will vanish after rewinding and syncing up to the new chain tip
