### ISSUE TITLE
Check pairing of deallocations vs allocations in rustBackend

### ISSUE THREAD

**Issue by LukasKorba** [zcash/ZcashLightClientKit#1262]
Comment in review `If I'm not mistaken rootsPtr is leaked because it's not deallocated.` but as I can see there are other allocations that seem to me not deallocated properly.

**Comment by LukasKorba** [comment]
<img width="750" alt="Screenshot 2023-09-14 at 12 38 01" src="https://github.com/zcash/ZcashLightClientKit/assets/7198042/73c04878-6b4d-46b5-9bb0-3dc082258c08">

<img width="779" alt="Screenshot 2023-09-14 at 12 38 15" src="https://github.com/zcash/ZcashLightClientKit/assets/7198042/fffb3aba-ac32-4cc3-9411-74c5ffe3339a">

**Comment by LukasKorba** [comment]
Leak number 1 is probably a false positive.

The allocation is done in the rust 
```
        let encodedKeysPtr = zcashlc_list_transparent_receivers(
            dbData.0,
            dbData.1,
            account,
            networkType.networkId
        )
```

and deallocation is handled in 
```
        defer { zcashlc_free_keys(encodedKeysPtr) }
```

Leak number 2 deallocated in the [code](https://github.com/zcash/ZcashLightClientKit/pull/1272) and after instruments check, this one no longer appears.

**Comment by daira** [comment]
Seems like this can be closed.
