### ISSUE TITLE
Remove rewind for every verify scan range

### ISSUE THREAD

**Issue by daira** [zcash/ZcashLightClientKit#1266]
The verify scan range doesn't require a rewind to be called. This is the ZcashLightClientKit equivalent of https://github.com/zcash/zcash-android-wallet-sdk/issues/1241.

**Comment by LukasKorba** [comment]
This is already done on iOS. Once we discovered in the review process of the SBS branch I created the [1241](https://github.com/zcash/zcash-android-wallet-sdk/issues/1241) for Honza because he is on vacation.
