### ISSUE TITLE
Transparent transactions not returned from `SDKSynchronizer.allTransactions()`

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1271]
### Describe the issue
Please provide a general summary of the issue you're experiencing

Our application is calling `allTransactions()` on the SDKSynchronizer object, expecting transparent transactions to be included in the list. Instead, only shielded transactions are present.

#### If so, please list the steps to reproduce below:
1. Checkout repo https://github.com/nighthawk-apps/nighthawk-ios-wallet/tree/feature/backup-settings
2. Run app in Xcode on a simulator or physical device.
3. Create a new wallet or restore an existing one.
4. Send funds to the transparent address of the wallet
5. Let the wallet sync completely

### Expected behaviour
Tell us what should happen

Upon sync completion, the app should show a transparent balance and should query for all transactions. On the transaction history screen, the transparent transaction you just sent should be visible.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

If the above steps were performed on a fresh wallet, even after the transparent txn is synced and the balances are updated, the list of transactions will still be empty. If done with an existing wallet, only previous shielded transactions will show in txn history.

- App Version: 2.0
- iOS Version: iOS 17
- Device: (if applies) iPhone 14 Pro Max

**Comment by LukasKorba** [comment]
This should be addressed in [rc2](https://github.com/zcash/ZcashLightClientKit/releases/tag/2.0.0-rc.2), pleazse try.

**Comment by tw0po1nt** [comment]
@LukasKorba i can confirm that I am seeing incoming transparent transactions, thank you. ![image](https://github.com/zcash/ZcashLightClientKit/assets/66689851/f23004e6-f131-4856-923b-5dd4d031d6da)

**Comment by LukasKorba** [comment]
Closing as resolved
