### ISSUE TITLE
Backgrounding app client causes errors from the synchronizer

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1278]
### Describe the issue
Please provide a general summary of the issue you're experiencing

When the app client that consumes the SDK goes to the background, rather than elegantly handling it, the SDK returns non-user friendly errors.

#### If so, please list the steps to reproduce below:
1. Load up Zashi Wallet (0.0.1 build 56) or [Nighthawk 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet/tree/feature/backup-settings)
2. Sync a wallet
3. Background the app - **without fully closing it** -  for a while (a minute or so should do it)
4. Bring the app to the foreground again

### Expected behaviour
Tell us what should happen
The app should be in a good state, no errors, and the SDK synchronizer should start up.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

The app relaunches and immediately the synchronizer returns an error.
![IMG_1498](https://github.com/zcash/ZcashLightClientKit/assets/66689851/c884a7c5-c9a6-42e1-9eed-6729c4618029)
![IMG_1499](https://github.com/zcash/ZcashLightClientKit/assets/66689851/cf156a80-bd14-4a99-b17d-ebdbc85f3d71)

- App Version: Nighthawk 2.0 (see github link above for code to pull) or Zashi 0.0.1 build 58 (latest TestFlight)
- iOS Version: iOS 17
- Device: (if applies) iPhone 14 Pro Max

**Comment by LukasKorba** [comment]
@tw0po1nt this is something I've had in mind for several weeks "what would happen if the synchronizer is sincing and the app suspended?". I discussed it with Honza, an Android developer and they do what I supposed must be done on iOS as well. When the app is going to the background, they call stop() on  Synchronizer and as opposite, they call start() once the app is going back to the foreground. Something demoapp nor Zashi do. I think this is needed to avoid an issue described here. SDK doesn't know anything about app's lifecycle so it must be the client in control over the SDKSyncrhonizer's state.

**Comment by tw0po1nt** [comment]
Yes, that is what Adi and I discussed as well. Wanted to bring it up here in case there was anyway the SDK could handle this more elegantly, but you're right. This specific problem requires an app level solve. Thanks for looking into it.

**Comment by LukasKorba** [comment]
Closing here but filed and [issue](https://github.com/zcash/secant-ios-wallet/issues/826) on Zashi side, we will need to implement the same behaviour.
