### ISSUE TITLE
Transaction history entries for shielding transactions are showing incorrect amounts

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1293]
### Describe the issue
Please provide a general summary of the issue you're experiencing
In Nighthawk, I autoshield my funds and expect to see a wallet event for it. I see an outgoing txn with the proper memo, but the amounts are wrong.

#### If so, please list the steps to reproduce below:
1. Launch [Nighthawk 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet)
2. Import a wallet with transparent funds or create a new wallet and send transparent funds to it
3. When the transparent funds are available to spend, swipe to the transparent balance tab in the home balance carousel.
4. Observe the "Shield now". Press it.
5. Tap the "Great!" button to confirm shielding
6. Observe that your transparent balance is now correct at 0 ZEC (or TAZ if using testnet)
7. Find the outgoing transaction in the list of recent events, or navigate to the full transaction history by tapping "View transaction history"
8. Observe the transaction details

### Expected behaviour
Tell us what should happen

I expect to see the correct net value delta of the transaction at the top, as well as in a line item at the bottom. 

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

Instead of the correct amount, I see what appears to be only the fee.

- App Version: 2.0.0
- iOS Version: iOS 17
- Device: (if applies) N/A

### Any extra information that might be useful in the debugging process.

![Simulator Screenshot - iPhone 15 Pro Max - 2023-09-28 at 08 17 06](https://github.com/zcash/ZcashLightClientKit/assets/66689851/245e9188-00d8-42b8-b734-1865bebad5f6)

![Simulator Screenshot - iPhone 15 Pro Max - 2023-09-28 at 08 27 09](https://github.com/zcash/ZcashLightClientKit/assets/66689851/b404f74c-f41d-41fe-ba24-030cd688b01f)

**Comment by nuttycom** [comment]
If you need to see the value of the shielded output, this is available from the transaction outputs. But I think it would be confusing to show the full shielded amount as received.

**Comment by nuttycom** [comment]
@tw0po1nt given what I've described above, is there any action that needs to be taken here, or can this be closed?

**Comment by tw0po1nt** [comment]
This can be closed. How to resolve the UX confusion can be discussed further in Discord
