### ISSUE TITLE
SDKSynchronizer.wipe() only works correctly if done while the synchronizer is running

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1297]
### Describe the issue
Please provide a general summary of the issue you're experiencing

I noticed that nuking a wallet in Nighthawk was failing, but it had previously worked, so I dug into it. If I nuke a wallet using the SDKSynchronizer.wipe API, the logic will correctly land me back on the onboarding flows. But if I close the app and re-open it after doing so, when the app checks the wallet initialization state, it errors out saying the keys are missing but the database files are present. So something is incorrectly re-generating the db files after a nuke. After further testing, I discovered that nuking does work if the synchronizer is still running when I perform the nuke.

#### If so, please list the steps to reproduce below:
Two scenarios:

Scenario 1: The synchronizer is running

1. Launch [Nighthawk 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet)
2. Create a new wallet
3. While the first sync is running, tap the settings tab, then `Advanced`
4. Tap 'Nuke wallet', and confirm in the alert that appears.
5. Observe that the app takes you back to the initial welcome screen.
6. Close the app (completely remove it from the app switcher)
7. Relaunch the app
8. Observe that the app presents the initial welcome screen
This is the expected behavior for scenario 1.

Scenario 2: The synchronizer is not running

1. Launch [Nighthawk 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet)
2. Create a new wallet
3. Allow the first sync to complete
4. Tap the settings tab, then `Advanced`
5. Tap 'Nuke wallet', and confirm in the alert that appears.
6. Observe that the app takes you back to the initial welcome screen.
7. Close the app (completely remove it from the app switcher)
8. Relaunch the app

### Expected behaviour
Tell us what should happen

In both scenarios, the app should be cleared of all old data files (keys, database files, UserDefaults, etc)
which should leave the app on the initial onboarding experience.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

In scenario 2, at some as-of-yet-unknown point in the nuke flow, the database files are recreated, which causes the initialization code to think that DB storage for a wallet exists, but the keys are missing (because as a post-task to nuking, we clear the key storage), which results in the following alert, with nothing that the user can do to recover.

![Simulator Screenshot - iPhone 15 Pro Max - 2023-09-29 at 21 21 34](https://github.com/zcash/ZcashLightClientKit/assets/66689851/51103adc-35d5-4b4d-a5c0-585dfdd25c82)

- App Version: 2.0
- iOS Version: iOS 17
- Device: (if applies) N/A

**Comment by LukasKorba** [comment]
I'm investigating this issue, so far it works in Zashi. There's really nothing that could cause this issues because there is no real difference between these 2 scenarios. When the SDKSynchronizer is not syncing, it's even easier state. Normally I would expect wiping during syncing to be a problem. Investigation continues...

**Comment by LukasKorba** [comment]
@tw0po1nt so I tried [NH 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet) and I'm not able to replicate the issue. 3 attempts, all passed with no error thrown. Could you please help me out with the replication? Is the issue replicable 100% times on your side or happening only occasionaly?

**Comment by LukasKorba** [comment]
Many more attempts with no failure. I also tried to debug the code and there are no signs of database files to be re-created. `keysMissing` issue is exactly that, no keychain data but some DB files. The order all calls associated with the wipe is also right.

**Comment by tw0po1nt** [comment]
I'll try and get a screen recording of the issue. Added context it that I reproduced it with testnet target and in the iOS simulator.

**Comment by tw0po1nt** [comment]
@LukasKorba I was unable to repro this in my latest testing yesterday, so I'll close this.

**Comment by tw0po1nt** [comment]
@LukasKorba I am still seeing this intermittently, and some of our users have reported this as well. The wipe process seems to be inconsistent. I'd like to keep this issue open until it can be confirmed to be fixed.
