### ISSUE TITLE
Data missing when importing wallet from seed

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/ZcashLightClientKit#1306]
### Describe the issue
Please provide a general summary of the issue you're experiencing

When importing a wallet from seed (a seed generated by the same wallet, so no cross-wallet importing issues), there is some key data missing / incorrect on transactions:

1. Memos
2. Recipients

All of my inbound txns on my wallet have memos, but none of them are being properly scanned. For every txn in the wallet, the only recipient reported in the internal wallet address at index 0.

#### If so, please list the steps to reproduce below:
1. Load up [Nighthawk Wallet 2.0](https://github.com/nighthawk-apps/nighthawk-ios-wallet)
2. Import a wallet from seed which has some received and sent txns, some with memos.
3. Observe the transaction details

### Expected behaviour
Tell us what should happen

For sent transactions, the recipient should be available in the transaction data, and should not just refer to the internal account at index 0.

For transactions with memos, they should be present.

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

Recipients for all transactions refer to the internal account at index 0. 
No memos are present.

- App Version: 2.0
- iOS Version: iOS 17
- Device: (if applies) iPhone 14 Pro Max

**Comment by LukasKorba** [comment]
As confirmed by @tw0po1nt, fixed in [2.0.3](https://github.com/zcash/ZcashLightClientKit/releases/tag/2.0.3)
