### ISSUE TITLE
Finish contributing guidelines

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#150]

**Comment by braddmiller** [comment]
@lindanlee This needs to be sorted out between us

**Comment by lindanlee** [comment]
@lindanlee  will submit PRs to add contributing guides to android and iOS sdks, point to them from read the docs, and then this will be done.

**Comment by lindanlee** [comment]
Submitted contributing guidelines to the two missing repos. 

Added link to contributing guides from read the docs. 
![image.png](https://images.zenhubusercontent.com/5db9eaacd077fc00017cc2f2/de9003db-4d1c-4f2b-8cf1-5a6d1e9084d4)
