### ISSUE TITLE
add extension function to identify inbound v. outbound txs on a client side

### ISSUE THREAD

**Issue by esengulov** [zcash/ZcashLightClientKit#206]

**Comment by pacu** [comment]
will this suffice for you  @esengulov?
```
public extension ConfirmedTransactionEntity {
   var isOutbound: Bool
   var isInbound: Bool
}
```

**Comment by esengulov** [comment]
> will this suffice for you @esengulov?
> 
> ```
> public extension ConfirmedTransactionEntity {
>    var isOutbound: Bool
>    var isInbound: Bool
> }
> ```

that works!

thanks Pacu and sorry it took me a while to get back on this, somehow missed it :)
