### ISSUE TITLE
Improve API method to request transaction history

### ISSUE THREAD

**Issue by esengulov** [zcash/ZcashLightClientKit#208]
provide API method to request transaction history in a manner where we can provide a transaction UID (OR transaction object) and obtain transactions that took place before it, with an option to specify how many transactions we need. 

`allTransactions(from transaction: TransactionEntity?, limit: Int).`

If transaction == nil THEN method should return transaction starting from latest (limit-count or less).

**Comment by gmale** [comment]
how about an API along these lines, based off of a query object (rather than a transaction):

```
getConfirmedTransactions (query: TransactionQuery)

interface TransactionQuery {
  offset?: number
  limit?: number
  startTimeMillis?: number
  endTimeMillis?: number
}
```

**Comment by esengulov** [comment]
> how about an API along these lines, based off of a query object (rather than a transaction):
> 
> ```
> getConfirmedTransactions (query: TransactionQuery)
> 
> interface TransactionQuery {
>   offset?: number
>   limit?: number
>   startTimeMillis?: number
>   endTimeMillis?: number
> }
> ```

thank you!
