### ISSUE TITLE
Shielded-Requirements not met on testnet 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#212]
When sending funds in testnet, this error comes up: occurs in both iOS and Android SDKs

````
ZcashLightClientSample[51523:1157962] [sample-logs] [ERROR :boom:] SendViewController.swift - send() - Line: 187 -> SEND FAILED: submitFailed(tx: ZcashLightClientKit.PendingTransaction(
toAddress: “ztestsapling1u09g72yke86a63vgxq9se6rfld3w9zmcvfxhqdrmdm2a6ek2sxxd9ephk0c22d2m2apqs9m0858”, 
accountIndex: 0, 
minedHeight: -1, 
expiryHeight: 1133459, 
cancelled: 0, 
encodeAttempts: 1,
 submitAttempts: 1,
 errorMessage: Optional(“18: bad-txns-shielded-requirements-not-met”), 
errorCode: Optional(-26), 
createTime: 1603305795.077002,
 raw: Optional(2373 bytes), 
id: Optional(1),
 value: 10000000, 
memo: Optional(17 bytes),
rawTransactionId: Optional(32 bytes)), errorCode: -26)
````

I’m running my own lightwalletd and zcashd and got the same error
consensusBranchId returned from librustzcash is  canopy	0xe9ff75a6

**Comment by gmale** [comment]
Quick update on some of what we've looked into so far:

- We've confirmed that lightwalletd has the right consensus branch id
- We've confirmed that the zcashd that lightwalletd is running on the v4.0.0 tag
- We've restarted and reindexed lightwalletd and zcashd

**Comment by str4d** [comment]
https://crates.io/crates/zcash_client_sqlite/0.2.1 fixes this issue.
