### ISSUE TITLE
[Data Access API] error decrypting transaction 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#230]
Reproducing Steps:
Start a Darksidewalletd server on localhost and run testReOrgChangesInboundTxMinedHeight
````
[ERROR 💥] CompactBlockEnhancementOperation.swift - main() - Line: 61 -> could not enhance txId 15a677b6770c5505fb47439361d3d3a7c21238ee1a6874fdedad18ae96850590 - Error: decryptError(error: ZcashLightClientKit.RustWeldingError.genericError(message: "Error while decrypting transaction: NOT NULL constraint failed: received_notes.is_change"))
````

**Comment by nuttycom** [comment]
This is a bug I introduced, there's a distinction between stmt_update_received_note and stmt_update_note in zcash_client_sqlite/src/scan.rs that I didn't catch.

**Comment by nuttycom** [comment]
@pacu https://github.com/zcash/librustzcash/pull/307/commits/d77784eba83b260f3a708eda5a8892a4741582a0 should fix this one.
