### ISSUE TITLE
cargo fails to build on Mac OS Big Sur

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#234]
We were reported that there are issues with the rust welding build and Mac OS X Big Sur.
Main issue being: `note: ld: library not found for -lSystem`
Due to the amount of user complaints about its stability we are currently not supporting that particular version of Mac OS X for now. 

We encourage all of our users and contributors to document the problem under this issue and send PRs with possible solutions. 

useful resources: https://community.intel.com/t5/Intel-Fortran-Compiler/New-macOS-Big-Sur-return-quot-ld-library-not-found-for-lSystem/m-p/1228382#M152647

````
platform name
iphoneos
cargo lipo --manifest-path /Users/ealymbaev/projects/bank-wallet-ios/Pods/ZcashLightClientKit/Cargo.toml --features=mainnet --targets aarch64-apple-ios --release
[INFO  cargo_lipo::meta] Will build universal library for ["libzcashlc"]
[INFO  cargo_lipo::lipo] Building "libzcashlc" for "aarch64-apple-ios"
   Compiling libc v0.2.79
   Compiling getrandom v0.1.15
   Compiling typenum v1.12.0
   Compiling proc-macro2 v1.0.24
   Compiling byteorder v1.3.4
   Compiling syn v1.0.42
   Compiling radium v0.4.1
   Compiling cc v1.0.41
error: linking with `cc` failed: exit code: 1

````

**Comment by ealymbaev** [comment]
https://developer.apple.com/forums/thread/666700

**Comment by ealymbaev** [comment]
https://github.com/ponylang/ponyc/issues/3684

**Comment by ealymbaev** [comment]
https://github.com/TimNN/cargo-lipo/issues/41
