### ISSUE TITLE
Max amount transactions are not reported as updated transactions when mined

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#255]
**What is the bug?**
When sending a transaction that involves all the available funds in a given seed, the SDK does not report back when the transaction is mined on the updated transactions event.

**Reproducing steps**

1. fund a wallet with some amount X (multiple notes)
2. sync the seed on additional device for control
3. send max amount (X - fee)  to someone 
4. wait for transaction to be mined on second wallet
5. verify that transaction is handled in originating device.

**Expected**: SDK should notify client if the transaction being updated
**Result**: transaction is still pending on originating device while it's properly  handled on second device.

**Additional context**
works fine when the transaction is Max amount - fee - 1 zatoshi.

**Comment by gmale** [comment]
That's so odd that the amount impacts notification. What do you think the root issue is here? Is there any chance of this occurring at the Rust level--and therefore on other platforms--or is this an issue with a notification not being triggered in a way that's specific to Swift?

**Comment by pacu** [comment]
yes, it's odd. I'm creating a test with darksidewalletd to reproduce this in an abstract client agnostic way.

**Comment by pacu** [comment]
It appears that the problem could be transactions that have no change output. Max Amount are the most common of the kind but given a note of  (X + Fee) Zec and a user sending X Zec to from that wallet should also produce this error

**Comment by str4d** [comment]
Haven't looked into this yet, but I'm almost certain it has the same root cause as https://github.com/zcash/librustzcash/issues/356 - assumptions being made about how the output-shuffling logic works for Sapling, that don't hold up in the case of no change.

**Comment by str4d** [comment]
I think https://github.com/zcash/librustzcash/issues/356#issuecomment-805513550 is at least a factor in this issue, if not the entire cause. This issue does not make clear under what recipient address types the issue occurs; if it is only occurring for sends to transparent addresses, that suggests it is exactly the linked problem.

**Comment by str4d** [comment]
@pacu could you see if https://github.com/zcash/librustzcash/pull/359 changes anything for you?

**Comment by pacu** [comment]
@str4d I checked out that branch and tested it with the same results.

**Comment by gmale** [comment]
Just to summarize: This issue was had multiple causes. Some for `z->t` transactions and some for `z->z`.

- `z->t` transactions were fixed by https://github.com/zcash/librustzcash/pull/359
- `z->z` transactions were fixed by https://github.com/zcash/librustzcash/pull/360

This issue now appears to be fully resolved.
