### ISSUE TITLE
Apple Silicon compatibility check 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#258]
The SDK "build system" has some assumptions on ACTIVE ARCHITECTURE that possibly won 't work on M1 chip apple computers. 

for example:
on `Scripts/build_librustzcash_xcode.sh` 

````
if [ $PLATFORM_NAME = "iphonesimulator" ]; then
    ZCASH_ACTIVE_ARCHITECTURE="x86_64-apple-ios"
else 
    ZCASH_ACTIVE_ARCHITECTURE="aarch64-apple-ios"
fi
````

this assumes that simulator builds use intel 64bit architecture which is no longer true
Same thing on `podspec`

````
    s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
    s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }

```

this makes simulator builds fail on m1 macs

**Comment by braddmiller** [comment]
Deliverables: 

- Minimum steps for LightClientKit to build on an M1 Mac
- write a README

Timebox: 4 hours (suggest attempting to allow Pacu to remote into the Dev Inf M1 mac)

**Comment by charlieok** [comment]
We got a successful build and running simulator on an m1 mac mini, by taking care to run a complete toolchain with Rosetta 2 enabled. The primary sticking points were making sure we had the corresponding rust toolchain and targets installed and selected.

<img width="1939" alt="Screen Shot 2021-03-24 at 2 03 39 PM" src="https://user-images.githubusercontent.com/7226/112376578-3ebf8580-8caa-11eb-92ae-378a385d6f28.png">
