### ISSUE TITLE
Error when sending:  18: bad-txns-sapling-duplicate-nullifier

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#261]
**What is the bug?**
after reproducing #255 the wallet has an inconsistent wallet state and subsequent txs fail

**Additional context**
check #255 

** reproducing steps ** 

1. send a tx with the maximum amount possible (available funds - fee)
2. let wallet sync past confirmations 
3. check pending transactions
4. navigate to block explorer on the sent transaction, verify that it was actually mined
5. check balance (it will show that you have available balance)
6. send a transaction of any amount (< that verified balance)

result: transaction fails with the error  18: bad-txns-sapling-duplicate-nullifier

**Comment by pacu** [comment]
Reported on ECC Wallet 0.3.5

**Comment by gmale** [comment]
Summary:
This bug was a symptom of #255, which has been resolved as fixed.
