### ISSUE TITLE
Connection problems when using VPN connection

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#264]
Nighthawk and Unstoppable user reported connection problems while using a supposedly good quality VPNs

captured error message: generic error 14

**Comment by braddmiller** [comment]
This is probably indicative of general brittleness in our LWD connection from the SDK. Most likely related to https://github.com/zcash/zcash-ios-wallet/issues/211 as well

**Comment by geffenz** [comment]
Assigning to myself for message categorization.

**Comment by geffenz** [comment]
Added to messaging, and done until future TOR work (grants) is done.
