### ISSUE TITLE
Research Spike: Update to new GRPC SDK

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#28]
The current GRPC SDK that we're using is being deprecated. We need to update to the latest version of Swift GRPC NIO. 

Findings: 
- SwiftGRPC NIO has no support for CocoaPods 
- can't be integrated as Swift Package at an SDK Level (except using Carthage, no thanks!)

Things to Explore:
- Fork the project and contribute with Cocoapod Support
- Support some sort of no so plug and play Swift Package Manager Support on the sdk

I created a question on their repo to find out the effort of supporting cocoapods on their end, so that we can decide whether we should contribute to those efforts or proceed to research how to support SPM in some manner

https://github.com/grpc/grpc-swift/issues/767

Well It turns out there's a pr in process for this!
https://github.com/grpc/grpc-swift/pull/764
let's see how it goes. I'll probably contribute on it if required

**Comment by pacu** [comment]
new ticket created on backlog
