### ISSUE TITLE
Sourcery not found on your PATH

### ISSUE THREAD

**Issue by StackHelp** [zcash/ZcashLightClientKit#300]
**What is the bug?**
I got the below error when tried to build the app

`/Users/abc/Erium-wallet/Pods/ZcashLightClientKit/Scripts/generate_zcashsdk_constants.sh: line 11: hash: sourcery: not found
Sourcery not found on your PATH
Command PhaseScriptExecution failed with a nonzero exit code
`

**Comment by adamstener** [comment]
Hi @StackHelp you'll need to have Sourcery installed and available on your path in order for the build to generate code that it needs to compile.  You can find instructions for this and other steps in the README file at the root of the project.

**Comment by StackHelp** [comment]
@adamstener I tried that but somehow not succeeded

**Comment by sagar-vaholiya** [comment]
@adamstener , I am also getting the same error. I checked on ReadME as you suggested, still not able to resolve this. And ReadME file, could not able to reach any solution so far.
Can you please guide more on this?

**Comment by pacu** [comment]
Hi @sagar-vaholiya.

Please refer to this section of the documentation https://github.com/zcash/ZcashLightClientKit/#installing-sourcery
