### ISSUE TITLE
[Assessment] Coding Guidelines and SwiftLint suggestions

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#310]
We've recently created Coding and Review Guidelines for contributors.
As a new contributor we'd like you to 

- proof-read the docs
- suggest changes, corrections or enhancements according to your best judgement and experience

repos: 
https://github.com/zcash/ZcashLightClientKit/
https://github.com/zcash/secant-ios-wallet

**Comment by geffenz** [comment]
@dh-ecc Daniel is this done? Can I close it?
