### ISSUE TITLE
Load Checkpoint files from bundle. 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#326]
## Is your feature request related to a problem? Please describe.
Since stencils are not being used anymore and given resource bundles can be achieved in SPM. Develop the functionality that allows the SDK to have JSON files with generated checkpoints for testnet and mainnet as the android SDK has.

## Describe the solution you'd like

- Stencil files are deleted if still available
- Huge Switch statements are deleted 
- the SDK includes two folders: `mainnet` and `testnet` for the corresponding checkpoints files
- the checkpoint files have 1 to 1 match with the GetTreeState JSON output from lightwalletd
- the files are called {CHECKPOINT_BLOCK_HEIGHT}.json
- their content is JSON
- the current public API does not change for the users

## Alternatives you've considered
- provide the option for wallet developers to supply their own checkpoints at runtime.

## Additional context
- corrupted or maliciously created checkpoints can be a threat to the user's funds. Procede with caution.

**Comment by geffenz** [comment]
This is for Daniel, who needs to be added to ZcashLightClientKit. IT request is aware.
