### ISSUE TITLE
M1 macs have problems with Swiftlint

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#343]
from @adamstener 

> On an M1 mac, you need to symlink your brew installed swiftlint over to the location where it would be if you had installed swiftlint with brew on a non-M1 mac. ` opt/homebrew/bin` -> `/usr/local/bin`

> If you symlink these locations for swiftlint and swiftgen, then we don't need to make any project modifications.

Things to do:

Add troubleshooting steps on the README section to explain this.

**Comment by LukasKorba** [comment]
Actually Sample project can be built with no issues, the swiftlint is not set to 0.45.0 like in secant-ios-wallet case. Closing as invalid
