### ISSUE TITLE
rename BlockHeight `.nullProgress` to `.nilProgress` 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#350]
rename BlockHeight `.nullProgress` to `.nilProgress` 

see comment from @adamstener in https://github.com/zcash/ZcashLightClientKit/pull/347

**Comment by adamstener** [comment]
My suggestion would be to factor this out completely and remove it, as having it is a code smell.
If there is no way around having this zero based initializer, the proper name would be `.zero`.
