### ISSUE TITLE
Expose an API that expresses syncing progress more clearly

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#434]
## Is your feature request related to a problem? Please describe.
When syncing, users don't know how far behind they are in terms of calendar days. Since progress % number resets between app launches it's hard for them to make a sense to that number.

## Describe the solution you'd like
I'd like the Synchronizer to expose emit a better client status
- Last synced block height
- Last sync block timestamp
- Latest block height
- Latest block timestamp
- Sync session ID
  - This ID will be the same within the same app launch. Client applications can use it to track sync progress across  app launches as they please by saving these statues somewhere.

From android repo

> 2. Improve the data incorporated into each state.  Syncing is the most important, and should have the following information
>     1. Sync session ID - an opaque globally unique string that changes each time a new sync starts. This is implemented as a string, but as an implementation it could be a UUID
>     2. Sync start time
>     3. Height of last block downloaded
>     4. Timestamp of last block scanned
>     5. Height of target block (e.g. tip of chain).  This may change repeatedly over time as the chain grows during a sync
>     6. Timestamp of target block
> 
> Clients can then determine whether to show users a percentage, date of last synced block, height of last synced block, or something else.  With the use of sync session ID and timestamp, clients can also better differentiate and remember whether sync has ever completed and decide how to display to the user when an incomplete sync is resumed in the future.

**Comment by nuttycom** [comment]
Fixed in #1239
