### ISSUE TITLE
Resilient reorg handling (in case of power loss, inattentive developer, etc)

### ISSUE THREAD

**Issue by defuse** [zcash/ZcashLightClientKit#49]
I predict this will be a common security bug pattern:

1. There's a reorg.
2. That reorg invalidates some data in memory, in a database, or in the UI.
3. That data isn't deleted / marked as invalid, because the code to do so was forgotten / wasn't written, or there's a power failure / unhandled exception in that code.

#44 is an instance of this pattern. Let's think a little bit about what we can do to make these bugs less likely. @pacu and @gmale, you know what developers expect/like best so your input will be really important here!

The current design is to have the developer listen for events indicating there's been a reorg and write some code to update their data structures / UI in response to what changed, which is really susceptible to this kind of bug because event handlers might not be guaranteed to run (in case of power failure / crash) or the developer might forget to listen for them.

Another idea is to expose a single source of truth for wallet data, which is kept up to date by the SDK, and an event simply notifes developers when "something changed" (reorg, new transaction, etc) and in that event the developer completely re-generates their entire UI, other data structures, etc, from the single source of truth, so that there's no chance of the UI or anything becoming partially out of sync with the source of truth. This would probably create performance issues, so I'm wondering what other options there are. At the very least, can we have the SDK double-check the developer is listening to all the events they need to? Any other ideas?

**Comment by braddmiller** [comment]
This ticket seems to have been superseded by the more detailed reorg testing and darksidewalletd
