### ISSUE TITLE
Send transaction fails with error when memo is nil

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#543]
### Describe the issue
Currently Secant iOS app uses empty String when user doesn't provide any memo while sending ZECs. So everything is fine and working. 

In `SDKSynchronizer.sendToAddress` method `memo` parameter is `String?`. Which means that memo doesn't have to only empty String but it can be also `nil`. But if `nil` is used then transaction fails with `ZcashLightClientKit.RustWeldingError or error 0`. 

<img width="395" alt="Screenshot 2022-09-24 at 13 46 53" src="https://user-images.githubusercontent.com/506376/192096298-d5f47d90-b7f7-4751-bf53-2d3d88b14605.png">

#### If so, please list the steps to reproduce below:
1. Call `SDKSynchronizer.sendToAddress` method and use `nil` value for `memo` parameter.

### Expected behaviour
Transaction should succeed without memo.
`SDKSynchronizer.sendToAddress` should be either changed to work with `nil` value or type of `memo` parameter should be changed to `String`.

### Actual behaviour + errors
Transaction fails with `ZcashLightClientKit.RustWeldingError or error 0`.

**Comment by pacu** [comment]
I'm trying to. reproduce the issue on version 0.16.10-beta and I'm not being able to.

Steps I'm doing:
- run darksidewalletd 
- change spend on `testReOrgChangesOutboundTxMinedHeight` from `"this is a test"` to `nil`
- launch `testReOrgChangesOutboundTxMinedHeight` tests

According to the bug description, It should fail but it doesn't.

I'm checking `main` of secant wallet and it appears to be using an old version of the SDK

````
0DB4E0B22881FD9100947B78 /* XCRemoteSwiftPackageReference "ZcashLightClientKit" */ = {
			isa = XCRemoteSwiftPackageReference;
			repositoryURL = "https://github.com/zcash/ZcashLightClientKit/";
			requirement = {
				kind = exactVersion;
				version = "0.16.6-beta";
			};
		};
````

Could you upgrade to 0.16.10-beta and try again ?

**Comment by Chlup** [comment]
I upgraded SDK in Secant to 0.16.10-beta and this issue is fixed.
