### ISSUE TITLE
`testReOrgRemovesOutboundTxAndIsNeverMined` fails

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#552]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/fc6183d0-52e1-4b14-9aa1-658b10e55d5f)

After merging latest master changes to this PR this test fails

**Comment by LukasKorba** [comment]
@pacu fixed the issue so this ticket is no longer valid. There was a merge issue when some test code was expluded.
