### ISSUE TITLE
Backup flow circular image frame broken

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#560]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/90b1e17b-99d2-49bb-9589-ce3f3e3ae897)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/9e71f8e4-e80c-4837-acea-86ecb522a316)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/2c6c74bd-2f98-41ae-98ee-2a4ce086c620)

**Comment by Chlup** [comment]
This should be created in Secant repo. 
https://github.com/zcash/secant-ios-wallet/issues/434
