### ISSUE TITLE
Verify that interrupted downloads of Sapling Parameters can be resumed

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#630]

**Comment by LukasKorba** [comment]
I'm confident our solution covers all edge cases and will always ensure valid sapling (spend, output) param files are in place, here's why:

- We use URLSession to download the files. Only when file is successfully downloaded is moved to the final destination. This final destination is also used in `isFilePresent()`. So failed download will throw an error and another call of `downloadParamsIfnotPresent` will start the process again.
- With #631 in place even successfully downloaded but corrupted file(s) will throw and error and remove the files from the final destination, causing restart when `downloadParamsIfnotPresent` is called again.
- However there's no logic in place that retries to download automatically. It's on a developer to call `downloadParamsIfnotPresent` again.

Unless we want to change anything or enhance the current solution I consider this task adept to be closed. @pacu @Chlup your thoughts?
