### ISSUE TITLE
instrument a flow to recover from corrupted or invalid Sapling parameter files

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#632]

**Comment by LukasKorba** [comment]
The [comment](https://github.com/zcash/ZcashLightClientKit/issues/630#issuecomment-1324851492) on #630 covers all we need for this one. I suggest to close the ticket. 

More detailed:
Actually we already have such API. As long as user of SDK calls `downloadParamsIfnotPresent` everything will be fine. And that is the only public API user can call.
- no files -> download will happen
- fail during download -> next call of `downloadParamsIfnotPresent` starts over
- corrupted files -> SHA1 check will delete them and next call of `downloadParamsIfnotPresent` will start over

I see no other case, public API for the user to be able to recover from missing or failed sapling files is `downloadParamsIfnotPresent`.
