### ISSUE TITLE
[657_download_change] fails to resume syncing after being backgrounded

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#678]
use branch change_how_blocks_sync of ECC wallet

While syncing a testnet wallet on ECC Wallet go to home and wait for the OS to stop syncing.

Then tap the app on the simulator to bring it to foreground.

**Comment by Chlup** [comment]
@pacu What do you think?

**Comment by pacu** [comment]
I specifically checked the logs to know it had stopped logging and doing stuff and it had not changed the status of the processor. It's possible that it's hard to reproduce because there are many factors at play that we don't control. I can try to gather more info.

**Comment by Chlup** [comment]
@pacu I was testing this with changes from #691. And I tried everything. And I am not sure if I experienced the case that you described originally but it seems to me that with #691 it's fine.

**Comment by pacu** [comment]
let's mark that PR then with `Closes #678`
