### ISSUE TITLE
[Download Change] Existing wallets don't report progress.

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#705]
Scenario: 

Wallet has an existing cacheDB which is notoriously ahead of scanning progress.

Compact block processor will use this cached blocks and scan them, but it won't report any progress in between.

Notes:

I think it is because the updates are now done per whole batch, whereas if I do have a cache existing, it will only scan and not report anything

One alternative would be to actually take this into consideration.
The other would be preemptively delete the cache DB and start downloading.

The second one could be the most convenient:
1. If you have your disk filled up by the wallet, then your wallet won’t work and you can’t recover from that. Currently my CacheDb is 12 GB. Deleting the file upon starting syncing would be fixing any wallets facing this problem.
2. because the FsBlockDb PR will do the same. Delete the cache DB and start using the FsBlockDb

**Comment by Chlup** [comment]
This is fixed in [#708](https://github.com/zcash/ZcashLightClientKit/pull/708).
