### ISSUE TITLE
Add Swift GRPC Plugin To ZcashLightClientKit

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#725]
We want the generated code from the proto files to be always in sync with current Swift-GRPC version 

let's add the Swift-GRPC plugin to the SDK so that we can 
- build generated code on the fly
- but still have reproducible builds 

reference: https://github.com/grpc/grpc-swift

**Comment by Chlup** [comment]
This can't be done in a way we expected. Any generating of proto files depends on `protoc` binary. And this binary isn't distributed together with Swift-GRPC plugin. So if we do this we will bother all the developers that use SDK to have `protoc` installed even though they don't need it. Let's don't do this. At least not now.
