### ISSUE TITLE
Travis & Github Action CIs failing due to swiftlint

### ISSUE THREAD

**Issue by LukasKorba** [zcash/ZcashLightClientKit#726]
After #711 the CIs started to fail. Bitrise is fixed at the moment. Travis and GA aren't. The failure is caused by swiftlint being a plugin for the SPM and Xcode 14 version, that one is validating plugins and swiftlint is not passing. The solution is to inject flag `-skipPackagePluginValidation` for the `xcodebuild` command. Done on a Bitrise side, we need to figure out other CIs.

**Comment by Chlup** [comment]
We don't need to solve this because we [decided](https://github.com/zcash/ZcashLightClientKit/issues/711#issuecomment-1400204540) not to use Swiftlint SPM package plugin.
