### ISSUE TITLE
Update HTML Docs or remove them 

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#759]
Jazzy generated docs are old. 

Consider updating them or removing them completely

**Comment by Chlup** [comment]
I suggest to remove generated doc. I don't think it brings any value. Zcash SDK is open source and I bet that majority of developers will go to code and check any available documentation there.

**Comment by pacu** [comment]
I'm finding out if Read The Docs depends on these docs being here, otherwise I will delete them.
