### ISSUE TITLE
100% markup coverage of iOS SDK 

### ISSUE THREAD

**Issue by lindanlee** [zcash/ZcashLightClientKit#78]
Achieve 100% comment coverage of functions that wallet developers will or should use.

Pacu should write comments inline his Swift code next to each API call so that Jazzy can generate documentation that explains each function call. This is an initial pass, documentation can be polished off in a separate ticket.

Acceptance criteria: 
- [x] comments next to each function/call 
- [x] comments are in markup format

**Comment by pacu** [comment]
@lindanlee I'm going to document note-spending-v7 branch since it's the latest API we have.
