### ISSUE TITLE
Inspect Jazzy HTML output and determine if reformatting is needed

### ISSUE THREAD

**Issue by lindanlee** [zcash/ZcashLightClientKit#79]
we looked at other generated html sites that used Jazzy outputs, which looked good enough. But we haven’t generated our own and inspected the results. 

Acceptance criteria: 
- [x] Jazzy output of current comments as-is (no requirement on content or coverage) 
- [x] Determine if the HTML output is good enough/modern/stylizable (Brad approval req)

**Comment by pacu** [comment]
I believe that the generated HTML is modern and structured in a way that admits customization to some extent
[https://app.zenhub.com/files/185480114/b957e014-95ae-4153-9c0d-6c71b5fbaefe/download](https://app.zenhub.com/files/185480114/b957e014-95ae-4153-9c0d-6c71b5fbaefe/download)

**Comment by pacu** [comment]
@brad check the docs.zip I uploaded whenever you can (not blocking anything in particular)
