### ISSUE TITLE
Simplify Synchronizer Status

### ISSUE THREAD

**Issue by pacu** [zcash/ZcashLightClientKit#843]
Simplify states to
- Up to date -> app has finished catching up with the latest blockchain events and it's considered to be synced and waiting for new blocks to arrive
- Syncing -> app is syncing a significant range of blocks
- Refreshing. -> this is sync that is 1 or 2 blocks 
- Error -> some error has happened and can't be auto-resumed and needs user attention. 

android counterpart https://github.com/zcash/zcash-android-wallet-sdk/issues/967

**Comment by Chlup** [comment]
@pacu I guess you mean synchronizer status (aka `SyncStatus`) not state (aka `SynchronizerState`) right?

**Comment by Chlup** [comment]
I was thinking about this. I am not sure if we can simplify it that much. 

We either need to keep `unprepared` or say that `prepare()` must be called before each start. Without `unprepared` status the client doesn't know if it need to call prepare. We can say it must be called before each start. 

Our current policy is that client apps shouldn't think much and simply render UI for the status that the SDK provides. To decide if `Syncing` or `Refreshing` should be used the SDK first must make to call to GRPC to fetch latest height. And that may take some time. So the client app calls start and nothing happens before GRPC call is finished and before the SDK switches to `Syncing` or `Refreshing` status. And for this time user see same UI, not any progress, nothing. We should have some kind of `working` or whatever status for which the client app should render some "in progress" UI.

I have no idea how to compute progress when we merge syncing, enhancing and fetching status to one. I agree that it would be easier for the client app. We just have to come up with progress computation before we decide to do this.

I think we need to keep `synced` state. If we keep only "in progress" states then the client app doesn't know when the process finishes and when to render "process done" UI.

**Comment by ccjernigan** [comment]
> Our current policy is that client apps shouldn't think much and simply render UI for the status that the SDK provides. To decide if `Syncing` or `Refreshing` should be used the SDK first must make to call to GRPC to fetch latest height. And that may take some time. So the client app calls start and nothing happens before GRPC call is finished and before the SDK switches to `Syncing` or `Refreshing` status. And for this time user see same UI, not any progress, nothing. We should have some kind of `working` or whatever status for which the client app should render some "in progress" UI.

I think we can simplify this down.  When the SDK is first launched, it could report syncing as a heuristic.  It is highly likely the SDK is more than 1 block behind when a new synchronizer instance is constructed.

Refreshing is for the case that the user has been in the app for a while and it does periodic fetches of new blocks every ~30 seconds.  The goal is to prevent flickering during this periodic refresh, as the UI transitions from idle -> syncing -> idle currently.

The risk of flicker for app launch -> syncing -> idle is low because as you note the first fetch for largest block height is slower.  Also there's only 1 state transition here rather than two as in the case we're trying to handle.

**Comment by pacu** [comment]
If our goal is for clients to debounce Refreshing or show non intrusive UI cues, maybe the Status change could be Refreshing -> Syncing if there's work to do or Refreshing -> Up-To-Date if it's only refreshing.

we could treat every sync attempt as a refresh preemptively and then when the length of the block range to sync is determined we can send an update to the state and switch to syncing with the complete progress information.

**Comment by pacu** [comment]
We could argue that refreshing could be a helper function of a information-rich progress state.

````Swift
struct SyncProgress {
   var currentProgress: Height
   var targetheight: Height
   var nowSyncing: Date
   var targetDate: Date
   var syncID: UUID
}

extension  SyncProgress {
   var isRefreshing: Bool {
        // return a bool by checking if this block range is negligible under some criteria
   }
}
````

then a client could actually update their UI by debouncing or filtering refreshing states

````Swift
void setUpUI() {
    synchronizer.statePublisher
        .filter { !$0.progress.isRefreshing } 
        .map { $0.asPercentage }
        .receive(on: DispatchQueue.main)
        .sink { [weak self] in
             self?.progressGauge.setProgress($0)
        }
        .store(in: &disposeBag)
}
````
