### ISSUE TITLE
Stop using SDKMetrics as singleton

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#846]
`SDKMetrics` are now used as singleton. This should be changed and each instance of the `SDKSynchronizer` should have it's own instance of the `SDKMetrics`. Then this instance must be passed as dependency to each part of the SDK that needs it. And API must be added to synchronizer so client apps can get the right `SDKMetrics` instance.

**Comment by LukasKorba** [comment]
done, #862
