### ISSUE TITLE
Make logger aware of the alias

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#848]
`LoggerProxy` and `OSLogger` must be somehow aware of the Alias. It probably won't be easy. We have to come with solution how to pass Alias to `OSLogger` so it can be part of the logs. And it would be great to make this automatically. It would be great to keep logging as it right now (do logging via static methods of `LoggerProxy`).

**Comment by LukasKorba** [comment]
Done, #868
