### ISSUE TITLE
iOS Basic Reorg Integration Testing

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#91]
Create integration tests utilizing the darksidewalletd changes to test blockchain reorgs of various lengths in LightClientKit.

Requirements:
- [x] Implement interface to darksidewalletd API
- [x] A chain reorg of <10 blocks without a wallet-associated transaction
- [x] A chain reorg of >10 blocks without a wallet-associated transaction

Reference:
https://docs.google.com/document/d/1_pC-uD7FdG8sMqVuuAXOoi9jFJlT9o3_Bg-WvJMfpwo/edit

**Comment by lindanlee** [comment]
Points to be assigned after Taylor's meeting and explanation.
