### ISSUE TITLE
Advanced Reorg integration testing

### ISSUE THREAD

**Issue by braddmiller** [zcash/ZcashLightClientKit#94]
Create an integration test utilizing the darksidewalletd changes to test transactions being reorg-ed away in LightClientKit.

Requirements:
- [ ] Transaction moved to different block in event of a reorg
- [x] Transaction disappears in event of a reorg
- [x] Balance difference is accurately reflected after a reorg

Reference:
https://docs.google.com/document/d/1_pC-uD7FdG8sMqVuuAXOoi9jFJlT9o3_Bg-WvJMfpwo/edit

Master Wallet Testing Doc with Pseudocode for tests:
https://docs.google.com/document/d/1Kv53ZnH_NVvP-b-6zMnZSCFk3k8sD-VlyGp40LMHczM/edit#

**Comment by lindanlee** [comment]
Clarification: This is just assuming that the tests are in place, not assuming that the tests will pass nor that the fixes will be in place.
