### ISSUE TITLE
Use Swiftdoc to generate documentation from ZcashError

### ISSUE THREAD

**Issue by Chlup** [zcash/ZcashLightClientKit#957]
Some investigation must be done to come up with solution for this.

**Comment by Chlup** [comment]
@pacu What we want to achieve exactly here? What should be the output? Should the documentation be visible in the Xcode? Or it will be some html file hosted somewhere? Or should it be markdown file that can be read here on github? 

I tried to investigate SwiftDoc and it is not standalone tool that generates files on disk. If you open project and in Xcode hit Product -> Build Documentation then SwiftDoc is used. And when this is done it opens Xcode developer documentation and include your project in there. So it works nice but only for Xcode users. That's why I am asking what is the target here.

**Comment by Chlup** [comment]
@pacu What should be the goal here? How the output should looks like? Should it be markdown file that can be viewed here on github? Or should it be html that will be hosted somewhere? Or something else?

**Comment by pacu** [comment]
https://developer.apple.com/documentation/xcode/documenting-apps-frameworks-and-packages

I think that what we'd like to make sure is that docs are viewable in-line with the code, that the code is the source of truth of documentation and that if desired, users can build the docs to see in "quick help". but nothing more for now.
